FROM ghcr.io/graalvm/native-image-community:21 AS builder
WORKDIR /build
RUN microdnf install -y maven && microdnf clean all
COPY . .
RUN mvn -pl shared-core,dispatch-service -am package -Pnative -DskipTests

FROM ubuntu:22.04
WORKDIR /app
COPY --from=builder /build/dispatch-service/target/dispatch-service app
EXPOSE 8080
ENTRYPOINT ["./app"]
