FROM ghcr.io/graalvm/native-image-community:21 AS builder
WORKDIR /build
RUN microdnf install -y maven && microdnf clean all
COPY . .
RUN mvn -pl shared-core,cluster-framework,cluster-sample -am package -Pnative -DskipTests

FROM ubuntu:22.04
WORKDIR /app
COPY --from=builder /build/cluster-sample/target/cluster-sample app
EXPOSE 8081
ENTRYPOINT ["./app"]
